### ISSUE TITLE
Fix Chain on Both ends

### ISSUE THREAD

**Issue by MianSalmanJavaid** [forestrf/Fake-hanging-chains#1]
Dear Creator, I have seen that you have fixed the chain from one end with the cube but on the other side it breaks its link with the sphere when you drag it after a certain limit. i have seen that the rest of the physics doesn't change much.. if i were to request you to tell how to make certain changes so that the chain can be fixed from both ends with the cube and you can then use that chain in game in which one end is attached to a car and another to an object which is being dragged by the car using that chain.. will your asset be able to manage something like that.. any reply from your side will be much appreciated.

**Comment by forestrf** [comment]
It is possible, indeed. It worked like that in the past, but I don't remember right now how to change it.

**Comment by forestrf** [comment]
I added an option to allow the stretching of the chain/rope: 52314b2eb32e6fddeae69a55cd52b224b5808171.
The transition between hanging and stretched is not as smooth as it could be, but it works.

**Comment by forestrf** [comment]
I added an option to allow the stretching of the chain/rope: 52314b2.
The transition between hanging and stretched is not as smooth as it could be, but it works.
